### ISSUE TITLE
In Call volume

### ISSUE THREAD

**Issue by hmespana** [boulzordev/android_device_lenovo_A6020a40#14] opened 2017-01-17 17:43 UTC
I had an a6020l36 and The call volume doesn't work, still the same volume, when press Vol+ or Vol -

**Comment by karthick111** [comment] 2017-01-17 19:28
You mean,while you are in a call,you were not able to control volume ?

**Comment by hmespana** [comment] 2017-01-17 19:46
yes, this is  the problem

**Comment by karthick111** [comment] 2017-01-17 19:47
Take a logcat while you are in call

**Comment by hmespana** [comment] 2017-01-17 20:01
the thing is the volume control respond to the buttons but, the sound is the same,  ill take the log soon as posible

**Comment by hmespana** [comment] 2017-01-17 20:31
[log_file.txt](https://github.com/boulzordev/android_device_lenovo_A6020/files/712260/log_file.txt)
Here is logfile

**Comment by danielstuart14** [comment] 2017-01-31 01:11
same here, which one is your variant @hmespana ?
Do you have any other sound issue? (Noise, crackling, etc.)

**Comment by netship01** [comment] 2017-01-31 01:41
@danielstuart14 
All variant have crackling sound issue during notification and at during boot.
And also there is offline charging issue.

**Comment by danielstuart14** [comment] 2017-01-31 02:20
that's good to know, I though it was only with L36. We'll be easier to track the issue.

Offline charging isn't working?

**Comment by netship01** [comment] 2017-01-31 03:24
Yeah! Offline charging is buggy(not working)
Actually it shows charging animation and charging graph grows with time but when you ON your mobile same battery percentage (no gain).

**Comment by netship01** [comment] 2017-01-31 03:37
Bugs on custom ROMs are
1.Offline charging not working
2.Crackling sound during boot(only stops when you play some sound) and durning notification.
3.gravity sensors is buggy (reported by many XDA member)
4.time and date resetting at every boot
5.gyro sensor is buggy (can't confirm it because don't have VR but Facebook 3d video works for me, but some XDA member says it need calibration
"Joaquím:
Now I remember almost all the time my gyro fails in asphalt 8 was, for example, when I turn right and almost instantly turn left or something similar"
)
6.noise reduction mic is not working(reported by many XDA users and experience too)

**Comment by netship01** [comment] 2017-01-31 04:27
@danielstuart14

**Comment by danielstuart14** [comment] 2017-01-31 05:46
https://github.com/LineageOS/android_device_wingtech_wt88047/commit/ccfb54118ef60d6579518c95246e9f6b8a229729
https://github.com/LineageOS/android_device_wingtech_wt88047/commit/e39ff002148ed57747b220c4c1ce4e1908a9d37f

From here: https://github.com/LineageOS/android_device_wingtech_wt88047/commits/cm-14.1/  (wt88047 aka redmi 2 is made by wingtech, as our vibe k5.)

**Comment by danielstuart14** [comment] 2017-01-31 05:51
Also: 
https://github.com/LineageOS/android_device_wingtech_wt88047/commit/c9ce7fd3a2ad3489b7b055a55d9e796fc96de166

**Comment by danielstuart14** [comment] 2017-01-31 05:55
We are missing also, the libs for sensor calibration: 
https://github.com/boulzordev/android_vendor_lenovo_A6020/blob/cm-14.1/proprietary/vendor/etc/calmodule.cfg

They should be here: https://github.com/boulzordev/android_vendor_lenovo_A6020/tree/cm-14.1/proprietary/vendor/lib
And here:  https://github.com/boulzordev/android_vendor_lenovo_A6020/tree/cm-14.1/proprietary/vendor/lib64

PS: Note that libcalmodule_common.so is already being builded by our source.

about the sound, that's probably kernel-side

**Comment by danielstuart14** [comment] 2017-01-31 05:55
@skritchz 
@Shr3ps

**Comment by netship01** [comment] 2017-01-31 06:05
@chaubeyprateek
@karthick111
@darshan1205

**Comment by danielstuart14** [comment] 2017-01-31 06:07
https://github.com/CyanogenMod/android_device_motorola_victara/commit/55d585738358b9faa7ca1ed551841b3dc81f8061
that should fix the crackling during notification. (NOT the noise on restart, that is kernel side)

To fix that, we'd probably need to merge the audio changes from lenovo's kernel source.
Ex:
https://github.com/LineageOS/android_kernel_wingtech_msm8916/commit/100da061895b124b69cf22b995b40a6fa2bc4933
https://github.com/LineageOS/android_kernel_wingtech_msm8916/commit/8c742a5ef9f01a37b64065c28ad21446a51d56e0
(That's for redmi 2, we need to take the changes from our kernel.)

**Comment by netship01** [comment] 2017-01-31 06:18
@danielstuart14 noise reduction mic is not working(reported by many XDA users and experience too)

**Comment by skritchz** [comment] 2017-01-31 09:24
@danielstuart14 we already have the victara patch, now I'll take a look at the kernel side.

I already took a lot of the commits from lenovo's kernel regarding the audio part. But I can double check. The problem was that we only have a plain .zip without proper commit history.

For example this commit allowed the speaker to work
https://github.com/boulzordev/android_kernel_lenovo_msm8929/commit/64bfcb059094daf7384237ab9078353ed676a6a3

**Comment by skritchz** [comment] 2017-01-31 09:25
Oups I didn't see the comment on the common...

**Comment by danielstuart14** [comment] 2017-01-31 16:33
@skritchz what about using the lenovo's kernel source (would need some patches for working with nougat, for ex: selinux) and the sensor libs from stock (instead building them) ?

**Comment by scritch007** [comment] 2017-01-31 16:34
This is what we used to do. But it was the same

**Comment by danielstuart14** [comment] 2017-01-31 16:37
redmi 2 had some issues with sensors and audio. You can try talk with @kumajaya

**Comment by dev-harsh1998** [comment] 2017-01-31 16:59
@scritch007 is there really so much Need Of CAF merge ?

**Comment by dev-harsh1998** [comment] 2017-01-31 17:01
Why don't we only pick needed Stuff like moto ?

**Comment by dev-harsh1998** [comment] 2017-01-31 17:03
@danielstuart14 is that a bad idea ? I am also Working on a Lenovo Device and I also have lenovo crap msm8916 kernel I have Tried both the ways which were merging CAF & 2nd way was only Picking needed Commits and Going Away and 2nd way really seems Better than Fucked up sound Effects I am currently Using Fully stable Nougat on my  Lenovo A6000 plus

**Comment by danielstuart14** [comment] 2017-02-01 02:09
just flashed aosp kernel on stock. (Replacing ramdisk.)
I got sound issues. So, it's definitely kernel side.

@dev-harsh1998 that's the best way.

**Comment by skritchz** [comment] 2017-02-01 09:23
@dev-harsh1998 The thing is that CAF kernel will keep up to date with the kernel CVE. so just updating to latest branch version is easy to trac. We can also see that lenovo's kernel sources aren't the latest one, and that they have some patches that the didn't provide. Support for a46 new version, support for the a40 new version too. 

We used to have the lenovo kernel for cm-13.0, but the sound issue was already reported there. https://forum.xda-developers.com/member.php?u=7723511 at that time we weren't on a CAF kernel.

@danielstuart14 what do you mean by aosp kernel?

So maybe we should try using your a6000 kernel, maybe there is one thing in there that I missed or a patch that was in your sources that actually fixes the sound issues.

**Comment by LuizPauloDamaceno** [comment] 2017-02-01 09:54
Here the audio problem is an white noise, i think is an HAL problem, i've build an custom kernel that works on stock roms too, the white noise didn't appear, this occours only with mm+ roms, with logcat i didn't see nothing wrong with audio service, but the noise stops when speakers are triggered with a just voulme switch click or notification sound... I think the solution for this is implementate a custom sound trigger at boot, the crackling sound can be solved updating some samplerates of audio policy.conf and adding one  config file (audio_output_policy.conf) this config file allows low latency playback to be used to play the notification sounds without delay.

**Comment by netship01** [comment] 2017-02-01 10:10
@luizpaulodamaceno 
True! If you flash vegito kernel on stock there is know crackling sound.
@scritch007

https://forum.xda-developers.com/k5-plus/development/kernel-vegito-kernel-lenovo-vibe-k5-t3512781/page22
See rohitsonone reply

**Comment by skritchz** [comment] 2017-02-01 10:21
@LuizPauloDamaceno which kernel did you use? caf base or lenovo base when testing on stock?

Ok so I'll focus on the audio HAL. I'm actually trying to make Dolby work again, but it requires patching lineage HAL too.

**Comment by LuizPauloDamaceno** [comment] 2017-02-01 10:32
Yes, i tried to change some variables, compile, but is license key variables and when boots on logcat i see lot of errors, with the dolby app nothing wrong occours. I'm using caf 14.1 base.

**Comment by skritchz** [comment] 2017-02-01 10:34
Great for the base. So issue is somewhere else but not in the kernel.
Now regarding Dolby, I never tried it, but I read somewhere in the cm13 it was working, although I didn't do anything for it.

**Comment by netship01** [comment] 2017-02-01 10:41
Dolby atom is flashable. Working great on nougat based ROM(currently using on RR N)

**Comment by skritchz** [comment] 2017-02-01 10:46
@netship01 are you sure it does something? Dolby support has been removed from the HAL layer :)

**Comment by LuizPauloDamaceno** [comment] 2017-02-01 10:49
I think dolby without HAL layer support just incrases CPU Load in audio processing and disables some effects, also, in my compilations i'm using Dolby DS1 DAP... Flashsable Dolby Atmos works grat in Nougat roms and some effects (not from equalizer) can be enabled with DS1 DAP...

https://github.com/LuizPauloDamaceno/android_vendor_lenovo_A6020/commit/6a6dea0dd1277a9732713f11577df98ea882286c
https://github.com/LuizPauloDamaceno/android_vendor_lenovo_A6020/blob/cm-14.1/proprietary/vendor/etc/audio_output_policy.conf

I added these two things... I think dolby DS1 / DS2 is just some "send parameters to DSP"

**Comment by netship01** [comment] 2017-02-01 11:02
https://drive.google.com/file/d/0ByloR06DONxLSGtSdGJZTUJ3dmc/view?usp=drivesdk 
I am using this

**Comment by skritchz** [comment] 2017-02-02 09:53
Do you guys have a logcat of a boot on Stock ROM please?

**Comment by LuizPauloDamaceno** [comment] 2017-02-02 11:09
In stock an error with audio_hw utils is reported in alogcat, but i don't have here because now i cant change my ROM... The problem can be solved addying audio_output_policy.conf file at /vendor/etc. This file also can set the samplerates, actually i have been maked one to work with N roms, i ddnt tested yet with stock, but i think works great too. the file is:  https://github.com/LuizPauloDamaceno/android_vendor_lenovo_A6020/blob/cm-14.1/proprietary/vendor/etc/audio_output_policy.conf

The stock samplerate is 48kHz but i seted to 192kHz (Supported by hal and kernel) to incrase audio fidelity... This doesnt generate an extra power consumption... I think will decrase in music listen because this will incrase the impedance of speaker and headphone coils because more frequency with same inductor generates more impedance.

**Comment by danielstuart14** [comment] 2017-02-02 15:29
@LuizPauloDamaceno the analog frequency (the one that goes to the speaker) won't change.
These frequencies you can change are related to the data that goes to DAC. Higher frequencies -> more data, and so, higher quality. 

Most speakers have a range from 20hz to 20khz, if samplerate changed analog frequencies you wouldn't be able to hear your musics as they are supposed to be.

![samplerate](http://www.labtronix.co.uk/images/Scope%20Sampling%201.gif)

**Comment by LuizPauloDamaceno** [comment] 2017-02-02 15:57
@danielstuart14  Sure, i forgot that point, the smartphones have DAC and probably later, one analaog amplifer (like class AB ones), so... the audio quality can be improved but the impedance not be changed because i think have some low pass filter before the amplifier. As we can see on the PWM signal with more frequency, more fidelity, because the signal will "pick more points" of the sinusoidal wave.

[http://www.vanatoo.com/uploads/images/class-d.jpg](url)

But, in fact, the "power" amplifier for speakers and headphones can be analog stage on power output.

**Comment by danielstuart14** [comment] 2017-02-08 01:12
So, I can say for sure, that the white noise on boot is related to IMS | VOLTE.

I builded cm-13.0 lineageOS, and the first build didn't had any audio issue. (Using cm-13.0 tree (from here), only changing cm_A6020 -> lineage_A6020, etc)

But, after I merged the commits related to IMS/VoLTE , the noise started.

Commits: 
https://github.com/AQSD/android_device_lenovo_A6020/commits/cm-13.0 (First build used cm-13.0 source from here with https://github.com/AQSD/android_device_lenovo_A6020/commit/5b41eb7deb6271547f200ce1ef1cbfd246dc3ed8)
https://github.com/AQSD/android_vendor_lenovo_A6020/commits/cm-13.0 (First build used cm-13.0 source from here.)

(I'm using cm-13.0 kernel by now, so, yeah, it's not the kernel.)

**Comment by danielstuart14** [comment] 2017-02-09 21:41
Yup, I removed VoLTE stuff from cm-14.1 and the sound issue stopped.
Maybe we can try kang it from wt88047

**Comment by LuizPauloDamaceno** [comment] 2017-02-09 23:08
I didnt think the issue is with IMS stuff... because in l36 variant (snap 616) since the first version of PAC ROM... But, here the issue is an white noise at boot, stops when speakers are triggered by a volume pulse or any another sound... The headphone, if sound isn't triggered, dont be reconciled, after white noise stops and sound triggered, everything works normally... So... When "audio_hw_primary" set the ACDB ID this stops, the setting occur when the audio is been triggered for any song:
Without audio trigger (white noise after boot, before sound trigger):
![screenshot_20170209-210236](https://cloud.githubusercontent.com/assets/22137326/22806948/b464815a-ef0b-11e6-98b0-e034ec1efabc.png)

With audio trigger (no white noise):
![screenshot_20170209-210243](https://cloud.githubusercontent.com/assets/22137326/22806971/d8a3a686-ef0b-11e6-9eca-97295c6350d3.png)

**Comment by danielstuart14** [comment] 2017-02-10 01:06
Well, it's indeed the IMS blobs. The question is why.
My guess is that when IMS service starts it sets an lower than minimum volume, then, when you change volume it sets it back to normal volume.

You can confirm it with the warning by SpeechLevelGenerator.

Check: 
https://github.com/AQSD/android_device_lenovo_A6020/commit/35184c558dcb71b8cbd005b56790a2c1e567fe05
https://github.com/AQSD/android_device_lenovo_A6020/commit/b8b6c9bb565ebce3273047ad044fa8a11764cdc4
https://github.com/AQSD/android_vendor_lenovo_A6020/commit/3a34e1a264673904095c7b1d671cc94431d10184


OBS: l36 variant here too, with these commits white noise was solved.

**Comment by skritchz** [comment] 2017-02-10 08:51
@danielstuart14 This is very strange. The boot noise is present since cm-13.0 and IMS has been added just very lately. I see that you made some cleanup, on the audio part. I did those changes to test but it didn't seem to work.

**Comment by danielstuart14** [comment] 2017-02-10 15:39
cm-13.0 doesn't have any audio issue here. Only got that after merging IMS stuff.

**Comment by skritchz** [comment] 2017-02-14 08:06
@danielstuart14 so I guess the issue wasn't VoLte, which commit(s) fixed the issue?

**Comment by danielstuart14** [comment] 2017-03-01 22:11
Fixed by this commit: https://github.com/boulzordev/android_kernel_lenovo_msm8916/commit/956729b6ad3bca7c7481fc01f078e85fdd65302c

@skritchz

**Closed as completed** 2017-03-02 13:47 UTC
